language: php
php:
  - 7.1.27
  - 7.3.4
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
    app: gicabus
install:
  -composer remove vendor/phpunit
  - composer install --no-interaction
  - composer update --no-interaction

script: phpunit --configuration ./application/tests/ --coverage-text