language: php
php:
  - 7.1.27
  - 7.3.4
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
    app: gicabus
install:
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi
script: phpunit --configuration ./application/tests/ --coverage-text